### ISSUE TITLE
Unable to display video poster image on main slide

### ISSUE THREAD

**Issue by monjitd** [Cosmitar/reactive-blueimp-gallery#2]
I am using a combination of images and videos to create a slideshow gallery. My videos are all mp4 files coming from a server. The videos on the gallery display the poster images, but the poster images does not display when the video thumbnail is clicked, but only the play button. Is there a way to also display the poster image at the back of the play button ?
![Screen Shot 2020-11-02 at 12 52 15 PM](https://user-images.githubusercontent.com/36118183/97901930-d37d1300-1d0a-11eb-9a60-b49dc788eaeb.png)
![Screen Shot 2020-11-02 at 12 55 29 PM](https://user-images.githubusercontent.com/36118183/97901950-db3cb780-1d0a-11eb-9e60-2dbcb26f2ff7.png)

**Comment by Cosmitar** [comment]
Hi @monjitd , based on BlueImp [documentation](https://github.com/blueimp/Gallery#multiple-video-sources) you can pass the `data-poster` attribute to set the mp4 video background.
I've tried myself on this project Storybook and seems to work.

Something like this
```javascript
const source = [{
  title: 'Back to school',
  href: 'http://0.s3.envato.com/h264-video-previews/80fad324-9db4-11e3-bf3d-0050569255a8/490527.mp4',
  type: 'video/mp4',
  poster: 'images/thumbnails/back-to-school.jpg',
  'data-poster': 'images/thumbnails/back-to-school.jpg', // <-- ADD THIS LINE
}]
```

**Comment by monjitd** [comment]
Worked like a charm ! Thanks !

> Hi @monjitd , based on BlueImp [documentation](https://github.com/blueimp/Gallery#multiple-video-sources) you can pass the `data-poster` attribute to set the mp4 video background.
> I've tried myself on this project Storybook and seems to work.
> 
> Something like this
> 
> ```js
> const source = [{
>   title: 'Back to school',
>   href: 'http://0.s3.envato.com/h264-video-previews/80fad324-9db4-11e3-bf3d-0050569255a8/490527.mp4',
>   type: 'video/mp4',
>   poster: 'images/thumbnails/back-to-school.jpg',
>   'data-poster': 'images/thumbnails/back-to-school.jpg', // <-- ADD THIS LINE
> }]
> ```

**Comment by monjitd** [comment]
Passing the 'data-poster' attribute did set the mp4 background.
